language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: 3aacfe8b5b095d54ca2128a4bc103641
    token: 3b2489c69c6fd0881fd3187d2276c65b37e5225a
script:

    # -Dtest=FileInfoTest --> Indica la classe di test da eseguire
  - mvn test -Dtest=FileInfoTest sonar:sonar -Pcode-coverage -Dsonar.projectKey=GlaAndry_bookkeeper -DfailIfNoTests=false -Dmaven.test.failure.ignore=true
