language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: 3aacfe8b5b095d54ca2128a4bc103641
    token: 3b2489c69c6fd0881fd3187d2276c65b37e5225a
script:

    # -Dtest=... --> Indica la classe di test da eseguire
  ##- mvn -Dtest=BufferedChannelTest verify -DfailIfNoTests=false sonar:sonar -Pcode-coverage -Dsonar.projectKey=GlaAndry_bookkeeper -Dmaven.test.failure.ignore=true
  - mvn verify -DfailIfNoTests=false sonar:sonar -Pcode-coverage -Dsonar.projectKey=GlaAndry_bookkeeper -Dmaven.test.failure.ignore=true
